### ISSUE TITLE
Licensing: open source-compatible licensing on used 3rd party libraries

### ISSUE THREAD

**Issue by GreyCat** [koczkatamas/kaitai_struct_webide#6]
The project uses a lot of 3rd party libraries now. Probably we'll need some clear "licensing" text, that will contain all of these licenses with references to particular files, copyright holders, etc, etc.

**Comment by GreyCat** [comment]
In more details, the proposal is to:

* Create a file like `LICENSE-3RD-PARTY.md`
* Walk through every one used 3rd party library or component.
* Get licensing of that component, append the following to the file:
  * A header that clearly states:
    * name of the component
    * which source files this licensing info applies to
  * Their license, verbatim copy (may be adjusted for formatting, if we'll use Markdown or something)
* Add some sort of "About" dialog box in the application, which will clearly list:
  * Name and version of the product (i.e. "Web IDE")
  * License of the main product
  * Version of Kaitai Struct compiler it uses (it is actually available as build info - see `io.kaitai.struct.MainJs().version` and `io.kaitai.struct.MainJs().buildDate`)
  * Summary of all the other 3rd party components we use, with links to read their licenses

To implement that "About" box with 3rd party licenses we'll probably need to process `LICENSE-3RD-PARTY.md` to generate some sort of JSON or something? Or we can just convert it to HTML and dump somewhere "as is" in one huge box (as actually most of proprietary products like Google / Samsung / etc / do).

[This stackexchange answer](http://softwareengineering.stackexchange.com/a/234526/123770) advices to do more or less the same.

**Comment by koczkatamas** [comment]
@GreyCat added licensing and version information. Could you take a look whether it looks okay to you?

**Comment by GreyCat** [comment]
Looks really cool! Thanks!

**Comment by GreyCat** [comment]
Just another thought: may be it's time to start some file like `DEVELOPERS.md`, to note all the development-related scripts / facilities available — like all these Python scripts, node.js JavaScript loaders, general practices on how to do the release / deployment, how to add more 3rd party components, etc.?
